# CircleCI Configuration for Next.js 15 project with Docker build and deploy
version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@2.8.1

jobs:
  build-nextjs:
    executor: node/default
    docker:
      - image: cimg/node:20.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --force
      - run:
          name: Set Node.js Environment
          command: echo 'NODE_ENV=production' >> $BASH_ENV

      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Build the Next.js project
          command: npm run build

      # Ensure artifacts directory exists and copy build artifacts
      - run:
          name: Prepare Build Artifacts
          command: |
            mkdir -p ~/artifacts/.next
            mkdir -p ~/artifacts/public
            cp -R .next/* ~/artifacts/.next/ || true
            cp -R public/* ~/artifacts/public/ || true

      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .next
            - public

  docker-build-and-push:
    executor: docker/default
    docker:
      - image: cimg/docker:24.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.16

      # Attach workspace before Docker build
      - attach_workspace:
          at: ~/artifacts

      # Add Docker build context preparation step
      - run:
          name: Prepare Docker Build Context
          command: |
            cp -R ~/artifacts/.next .next
            cp -R ~/artifacts/public public

      - run:
          name: Build Docker Image
          command: |
            docker build \
              --build-arg NEXT_BUILD_ID=${CIRCLE_SHA1} \
              -t vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest} .

      # Use environment variables for Docker credentials
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest}

workflows:
  build-and-deploy:
    jobs:
      - build-nextjs
      - docker-build-and-push:
          requires:
            - build-nextjs