version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@2.8.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.17.0

  docker-executor:
    docker:
      - image: docker:20.10.21
    working_directory: ~/project
    environment:
      DOCKER_BUILDKIT: 1
      TRIVY_VERSION: "0.34.0"

jobs:
  build-nextjs:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --force
      - run:
          name: Build the Next.js project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .next
            - public

  scan-dependencies:
    executor: node-executor
    environment:
      TRIVY_VERSION: "0.34.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --force
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | tar xz
            sudo mv trivy /usr/local/bin/
      - run:
          name: Verify Trivy Installation
          command: trivy --version
      - run:
          name: Scan Dependencies for Vulnerabilities
          command: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

  docker-build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prepare Docker Build Context
          command: |
            mkdir -p .next public
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --build-arg NEXT_BUILD_ID=${CIRCLE_SHA1} \
              -t vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest} .
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | tar xz
            sudo mv trivy /usr/local/bin/
      - run:
          name: Scan Docker Image with Trivy
          command: |
            trivy image --exit-code 1 --severity HIGH,CRITICAL \
              vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest}
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest}

workflows:
  build-and-deploy:
    jobs:
      - build-nextjs
      - scan-dependencies
      - docker-build-and-push:
          requires:
            - build-nextjs
            - scan-dependencies
