# CircleCI Configuration for Next.js 15 project with `npm install --force`
version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@3.2.1

jobs:
  build-nextjs:
    # Build Next.js project
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies with npm install --force
          command: npm install --force
      - run:
          name: Set Node.js Environment
          command: echo 'NODE_ENV=production' >> $BASH_ENV  # Ensure production environment
      - run:
          name: Build the Next.js project
          command: npm run build
      - run:
          name: Create the ~/artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy Next.js output to artifacts
          command: |
            cp -R .next ~/artifacts/.next 2>/dev/null || true  # Copy .next directory
            cp -R public ~/artifacts/public 2>/dev/null || true  # Copy public directory
      - store_artifacts:
          path: ~/artifacts
          destination: nextjs-build
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .next  # Persist the Next.js build artifacts
            - public  # Persist public assets
  docker-build-and-push:
    executor: docker/default
    steps:
      - checkout
      - setup_remote_docker:
           version: 20.10.16
      - attach_workspace:
          at: /workspace
      - run:
          name: Build Docker Image
          command: |
            docker build -t vathanaksol/cloudinator-ui:latest .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag Docker Image
          command: |
            docker tag cloudinator-ui:latest vathanaksol/cloudinator-ui:latest
      - run:
          name: Push Docker Image
          command: |
            docker push vathanaksol/cloudinator-ui:latest
workflows:
  build-and-test:
    jobs:
      - build-nextjs
      - docker-build-and-push:
          requires:
            - build-nextjs
