version: 2.1

orbs:
  node: circleci/node@5
  docker: circleci/docker@2.8.1
  trivy: cci-labs/trivy@1.0.0

executors:
  node-executor:
    docker:
      - image: cimg/node:20.17.0

  docker-executor:
    machine:
      image: ubuntu-2004:current
    environment:
      TRIVY_VERSION: "0.34.0"  

jobs:
  build-nextjs:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --force
      - run:
          name: Set Node.js Environment
          command: echo 'NODE_ENV=production' >> $BASH_ENV

      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Build the Next.js project
          command: npm run build

      - run:
          name: Prepare Build Artifacts
          command: |
            mkdir -p ~/artifacts/.next
            mkdir -p ~/artifacts/public
            cp -R .next/* ~/artifacts/.next/ || true
            cp -R public/* ~/artifacts/public/ || true

      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .next
            - public

  scan-dependencies:
    executor: node-executor
    environment:
      TRIVY_VERSION: "0.34.0" # Define the Trivy version explicitly
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install --force
  
      - run:
          name: Install Trivy
          command: |
            curl -sfL https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | tar xz
            sudo mv trivy /usr/local/bin/
  
      - run:
          name: Verify Trivy Installation
          command: trivy --version
  
      - run:
          name: Scan Dependencies for Vulnerabilities with Trivy
          command: |
            trivy fs --exit-code 1 --severity HIGH,CRITICAL . || true # Adjust severity as needed


    docker-build-and-push:
      executor: docker-executor
      steps:
        - checkout
  
        - attach_workspace:
            at: ~/artifacts
  
        - run:
            name: Prepare Docker Build Context
            command: |
              cp -R ~/artifacts/.next .next
              cp -R ~/artifacts/public public
  
        - run:
            name: Build Docker Image
            command: |
              docker build \
                --build-arg NEXT_BUILD_ID=${CIRCLE_SHA1} \
                -t vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest} .

        - run:
            name: Install Trivy
            command: |
              sudo apt-get update && apt-get install -y wget && \
              wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb && \
              dpkg -i trivy_0.18.3_Linux-64bit.deb && \
              rm trivy_0.18.3_Linux-64bit.deb

        - run:
            name: Scan Docker Image with Trivy
            command: |
              trivy image --exit-code 1 --severity HIGH,CRITICAL vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest} || true
        
        - run:
            name: Docker Login
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  
        - run:
            name: Push Docker Image
            command: |
              docker push vathanaksol/cloudinator-ui:${CIRCLE_SHA1:-latest}

workflows:
  build-and-deploy:
    jobs:
      - build-nextjs
      - scan-dependencies
      - docker-build-and-push:
          requires:
            - build-nextjs
            - scan-dependencies
